# Generated by Django 3.1.2 on 2020-10-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
